### ISSUE TITLE
Settings MYSQL Config file are not optimal for i-doit

### ISSUE THREAD

**Issue by Invidia1990** [Gubaer/gubaer.github.com#1] opened 2015-06-23 17:08 UTC
i-doit Installation will work, but they warn about the configuration of mysql.

This points should be diffrent:

max_allowed_packet should be at least 32M (currently 16.00M)!
query_cache_limit should be at least 4M (currently 1.00M)!
![2015-06-23 19_08_29-clipboard](https://cloud.githubusercontent.com/assets/13020958/8312120/3e8fe480-19db-11e5-9f74-b5593dc8f997.png)

**Comment by Gubaer** [comment] 2015-06-25 17:05
Duplicate of https://github.com/Gubaer/docker-i-doit/issues/1

Closing

**Closed as completed by Gubaer** 2015-06-25 17:05 UTC
